import type { GameSystem, ReadingSpread, ReadingSpreadConfig } from '@/types';

export const READING_SPREADS: Record<ReadingSpread, ReadingSpreadConfig> = {
	simple: {
		value: 'simple',
		label: 'Tiragem simples',
		description: 'Uma única carta para resposta rápida, presságio ou direção imediata.',
		columns: 1,
		rows: 1,
		positions: [
			{
				id: 'single',
				deck: 'both',
				name: 'Carta única',
				text: 'Esta carta revela o presságio central da leitura.',
				x: 1,
				y: 1,
			},
		],
	},
	'simple-cross': {
		value: 'simple-cross',
		label: 'Cruz simples',
		description: 'A tiragem padrão atual, com três cartas comuns e duas cartas altas.',
		columns: 3,
		rows: 3,
		positions: [
			{
				id: 'tome',
				deck: 'low',
				name: 'Tomo de Strahd',
				text: 'Carta 1: Esta carta determina a localização do Tomo de Strahd (descrito no apêndice C).',
				x: 1,
				y: 2,
			},
			{
				id: 'ravenkind',
				deck: 'low',
				name: 'Símbolo Sagrado de Ravenkind',
				text: 'Carta 2: Esta carta determina a localização do Símbolo Sagrado do Grande Corvo (descrito no apêndice C).',
				x: 2,
				y: 1,
			},
			{
				id: 'sunsword',
				deck: 'low',
				name: 'Espada Solar',
				text: 'Carta 3: Esta carta determina a localização da Solâmina (descrita no apêndice C).',
				x: 3,
				y: 2,
			},
			{
				id: 'ally',
				deck: 'high',
				name: 'Inimigo de Strahd',
				text: 'Carta 4: Esta carta determina onde os personagens poderão encontrar um poderoso aliado.',
				x: 2,
				y: 3,
			},
			{
				id: 'strahd',
				deck: 'high',
				name: 'Strahd',
				text: 'Carta 5: Esta carta revelada determinará onde o Strahd sempre pode ser encontrado.',
				x: 2,
				y: 2,
			},
		],
	},
	'extended-cross': {
		value: 'extended-cross',
		label: 'Cruz estendida',
		description: 'Variação ampliada da cruz, com passado e futuro em camadas.',
		columns: 5,
		rows: 5,
		cardHeight: 'min(15vh, 145px)',
		cardWidth: 'min(10.7vh, 104px)',
		gapClassName: 'gap-1 sm:gap-2 md:gap-3',
		positions: [
			{
				id: 'focus',
				deck: 'both',
				name: 'Foco',
				text: 'Carta 1: É, sempre, a carta do foco. Esta carta não é sorteada aleatoriamente, mas é selecionada do baralho de acordo com o alvo da busca e posicionada na posição 1.',
				x: 3,
				y: 3,
			},
			{
				id: 'recent-past',
				deck: 'both',
				name: 'Passado próximo',
				text: 'Carta 2: Representa um passado próximo. Indica a importância de eventos que ocorreram recentemente. É claro, a escala de tempo envolvida é muito arbitrária, então um “passado recente”, pode indicar uma hora, um dia, ou até mesmo um ano atrás.',
				x: 3,
				y: 4,
			},
			{
				id: 'opposition',
				deck: 'both',
				name: 'Oposição',
				text: 'Carta 3: É a oposição ao foco. Diferentemente da cruz anterior, ela não é o maior dos obstáculos do foco. Ela apenas indica um problema potencial que pode ser superado ou até mesmo prevenido com um pouco de planejamento ou precaução.',
				x: 2,
				y: 3,
			},
			{
				id: 'near-future',
				deck: 'both',
				name: 'Futuro próximo',
				text: 'Carta 4: É a contra-parte da carta 2. Ela marca coisas que os esperam em um futuro próximo. Novamente, “próximo” é um termo flexível.',
				x: 3,
				y: 2,
			},
			{
				id: 'aid',
				deck: 'both',
				name: 'Auxílio',
				text: 'Carta 5: Marca aquelas coisas que auxiliam o foco. Como a carta 3, ela não têm uma grande significância. Ela trata de coisas que possam passar desapercebidas ou desconhecidas se não forem tomados os devidos cuidados e precauções.',
				x: 4,
				y: 3,
			},
			{
				id: 'distant-past',
				deck: 'both',
				name: 'Passado distante',
				text: 'Carta 6: Remete a um passado distante. Indica as raízes mais profundas e antigas do foco. Como outras cartas de passado e futuro, o tempo refletido não é absoluto.',
				x: 3,
				y: 5,
			},
			{
				id: 'deep-opposition',
				deck: 'both',
				name: 'Força oposta',
				text: 'Carta 7: Indica forças que verdadeiramente se opõem ao foco. Diferentemente do que marca a carta 3, esta é uma força poderosa e determinada que fará tudo que puder para impedir ou derrotar os melhores esforços do foco.',
				x: 1,
				y: 3,
			},
			{
				id: 'distant-future',
				deck: 'both',
				name: 'Futuro distante',
				text: 'Carta 8: É a manifestação de um futuro distante. Representa os primórdios do assunto em questão, o foco. Novamente, a escala de tempo envolvida é impossível de se predizer.',
				x: 3,
				y: 1,
			},
			{
				id: 'strong-aid',
				deck: 'both',
				name: 'Força aliada',
				text: 'Carta 9: A última a ser revelada. Fala de uma força que poderosamente ajuda nos empreendimentos do foco. É a contra-parte da carta 7.',
				x: 5,
				y: 3,
			},
		],
	},
	tower: {
		value: 'tower',
		label: 'A Torre',
		description: 'Cruz divergente com raízes no passado e múltiplos futuros possíveis.',
		columns: 3,
		rows: 5,
		cardHeight: 'min(15vh, 145px)',
		cardWidth: 'min(10.7vh, 104px)',
		gapClassName: 'gap-1 sm:gap-2 md:gap-3',
		positions: [
			{
				id: 'focus',
				deck: 'both',
				name: 'Foco',
				text: 'Carta 1: É a carta do foco. Ela reflete o alvo de cuja informação é buscada. Esta carta não é sorteada aleatoriamente, mas é selecionada do baralho de acordo com o alvo da busca e posicionada na posição 1. Explique aos jogadores que está carta é o nexo por onde as outras cartas irão se formar.',
				x: 2,
				y: 3,
			},
			{
				id: 'past',
				deck: 'both',
				name: 'Passado',
				text: 'Carta 2: Representa o passado. Conta um pouco da história da carta de foco. Normalmente a correlação entre o significado desta carta com a carta de foco é fácil de ser fabricada. Se nenhuma relação óbvia ocorrer, o Mestre pode dizer que há ainda um mistério que os jogadores ainda não resolveram. Mais tarde, eventos podem ser desenvolvidos para dar significado a esta carta.',
				x: 2,
				y: 4,
			},
			{
				id: 'opposition',
				deck: 'both',
				name: 'Oposição',
				text: 'Carta 3: Indica coisas que são opostas ao foco. Sua natureza reflete coisas que podem dar errado, indivíduos que possam desafiar o foco, ou a influência de qualquer tipo de resultados negativos.',
				x: 1,
				y: 3,
			},
			{
				id: 'future',
				deck: 'both',
				name: 'Futuro',
				text: 'Carta 4: Representa o futuro. Ela adverte possíveis desastres e faz promessas de triunfos futuros. Seu significado é sempre alvo de especulações, pois as ações do foco podem alterar a leitura do tarokka.',
				x: 2,
				y: 2,
			},
			{
				id: 'aid',
				deck: 'both',
				name: 'Auxílio',
				text: 'Carta 5: Marca aquilo que é amigo ou aliado do foco. Indica as forças que irão beneficiar o foco na busca por seu objetivo final. Marca as forças a favor da carta do foco.',
				x: 3,
				y: 3,
			},
			{
				id: 'distant-past-left',
				deck: 'both',
				name: 'Raiz do passado',
				text: 'Cartas 6, 7 e 8: Marcam aspectos de um passado distante. Sua contribuição é combinada, formando uma imagem das raízes do presente que é muito mais substancial do que aquelas oferecidas pelo padrão da cruz simples e da extendida.',
				x: 1,
				y: 5,
			},
			{
				id: 'distant-past-center',
				deck: 'both',
				name: 'Raiz do passado',
				text: 'Cartas 6, 7 e 8: Marcam aspectos de um passado distante. Sua contribuição é combinada, formando uma imagem das raízes do presente que é muito mais substancial do que aquelas oferecidas pelo padrão da cruz simples e da extendida.',
				x: 2,
				y: 5,
			},
			{
				id: 'distant-past-right',
				deck: 'both',
				name: 'Raiz do passado',
				text: 'Cartas 6, 7 e 8: Marcam aspectos de um passado distante. Sua contribuição é combinada, formando uma imagem das raízes do presente que é muito mais substancial do que aquelas oferecidas pelo padrão da cruz simples e da extendida.',
				x: 3,
				y: 5,
			},
			{
				id: 'possible-future-left',
				deck: 'both',
				name: 'Futuro possível',
				text: 'Cartas 9, 10 e 11: Estas cartas carregam a predileção do futuro. Cada uma delas possui uma possibilidade diferente e divergente, e a que verdadeiramente representará o futuro irá depender das ações da pessoa representada pela carta de foco. O significado dessas cartas não forma uma imagem única, combinada, mas duas delas são possibilidades alternativas que nunca irão se materializar.',
				x: 1,
				y: 1,
			},
			{
				id: 'possible-future-center',
				deck: 'both',
				name: 'Futuro possível',
				text: 'Cartas 9, 10 e 11: Estas cartas carregam a predileção do futuro. Cada uma delas possui uma possibilidade diferente e divergente, e a que verdadeiramente representará o futuro irá depender das ações da pessoa representada pela carta de foco. O significado dessas cartas não forma uma imagem única, combinada, mas duas delas são possibilidades alternativas que nunca irão se materializar.',
				x: 2,
				y: 1,
			},
			{
				id: 'possible-future-right',
				deck: 'both',
				name: 'Futuro possível',
				text: 'Cartas 9, 10 e 11: Estas cartas carregam a predileção do futuro. Cada uma delas possui uma possibilidade diferente e divergente, e a que verdadeiramente representará o futuro irá depender das ações da pessoa representada pela carta de foco. O significado dessas cartas não forma uma imagem única, combinada, mas duas delas são possibilidades alternativas que nunca irão se materializar.',
				x: 3,
				y: 1,
			},
		],
	},
	pyramid: {
		value: 'pyramid',
		label: 'A Pirâmide',
		description: 'Tiragem usada para selecionar um curso de ação rumo a um evento final.',
		columns: 7,
		rows: 4,
		cardHeight: 'min(15vh, 145px)',
		cardWidth: 'min(10.7vh, 104px)',
		gapClassName: 'gap-1 sm:gap-2 md:gap-3',
		positions: [
			{
				id: 'focus',
				deck: 'both',
				name: 'Foco',
				text: 'Carta 1: Como sempre, é a carta do foco. É o centro da pirâmide, de onde as outras cartas farão o contorno.',
				x: 4,
				y: 3,
			},
			{
				id: 'opposition',
				deck: 'both',
				name: 'Oposição',
				text: 'Carta 2: Indica as forças que atualmente são opostas as ações do foco. Elas são normalmente poderosas, mas podem ser mais fracas que alguns casos.',
				x: 2,
				y: 3,
			},
			{
				id: 'allies',
				deck: 'both',
				name: 'Aliados',
				text: 'Carta 3: É o inverso da carta 2, representa os amigos ou aliados do foco. Pode possuir maior ou menor importância ou influência no futuro, dependendo da situação ou do desejo do Mestre.',
				x: 6,
				y: 3,
			},
			{
				id: 'past-darkness-left',
				deck: 'both',
				name: 'Passado',
				text: 'Cartas 4, 5, 6 e 7: Denota vários aspectos do passado. Elas não são interligadas como no padrão torre, mas cada uma delas possui sua própria significação. O conceito por trás da pirâmide é que uma série de eventos do passado levam a um único e inevitável evento futuro. Assim, cada uma dessas cartas são tomadas como o início de uma corrente de eventos que irão, no final, unir-se uns aos outros. As cartas 5 e 6 normalmente falam de maldade e escuridão, enquanto as cartas 6 e 7 assumem a representação da bondade.',
				x: 1,
				y: 4,
			},
			{
				id: 'past-darkness-right',
				deck: 'both',
				name: 'Passado',
				text: 'Cartas 4, 5, 6 e 7: Denota vários aspectos do passado. Elas não são interligadas como no padrão torre, mas cada uma delas possui sua própria significação. O conceito por trás da pirâmide é que uma série de eventos do passado levam a um único e inevitável evento futuro. Assim, cada uma dessas cartas são tomadas como o início de uma corrente de eventos que irão, no final, unir-se uns aos outros. As cartas 5 e 6 normalmente falam de maldade e escuridão, enquanto as cartas 6 e 7 assumem a representação da bondade.',
				x: 3,
				y: 4,
			},
			{
				id: 'past-light-left',
				deck: 'both',
				name: 'Passado',
				text: 'Cartas 4, 5, 6 e 7: Denota vários aspectos do passado. Elas não são interligadas como no padrão torre, mas cada uma delas possui sua própria significação. O conceito por trás da pirâmide é que uma série de eventos do passado levam a um único e inevitável evento futuro. Assim, cada uma dessas cartas são tomadas como o início de uma corrente de eventos que irão, no final, unir-se uns aos outros. As cartas 5 e 6 normalmente falam de maldade e escuridão, enquanto as cartas 6 e 7 assumem a representação da bondade.',
				x: 5,
				y: 4,
			},
			{
				id: 'past-light-right',
				deck: 'both',
				name: 'Passado',
				text: 'Cartas 4, 5, 6 e 7: Denota vários aspectos do passado. Elas não são interligadas como no padrão torre, mas cada uma delas possui sua própria significação. O conceito por trás da pirâmide é que uma série de eventos do passado levam a um único e inevitável evento futuro. Assim, cada uma dessas cartas são tomadas como o início de uma corrente de eventos que irão, no final, unir-se uns aos outros. As cartas 5 e 6 normalmente falam de maldade e escuridão, enquanto as cartas 6 e 7 assumem a representação da bondade.',
				x: 7,
				y: 4,
			},
			{
				id: 'near-future-evil',
				deck: 'both',
				name: 'Futuro próximo',
				text: 'Cartas 8 e 9: Marcam um futuro próximo. A primeira fala das forças do mal que estão à espreita, a segunda diz respeito as forças do bem que são opostas à carta de foco.',
				x: 3,
				y: 2,
			},
			{
				id: 'near-future-good',
				deck: 'both',
				name: 'Futuro próximo',
				text: 'Cartas 8 e 9: Marcam um futuro próximo. A primeira fala das forças do mal que estão à espreita, a segunda diz respeito as forças do bem que são opostas à carta de foco.',
				x: 5,
				y: 2,
			},
			{
				id: 'final-event',
				deck: 'both',
				name: 'Evento final',
				text: 'Carta 10: Forma o ápice da pirâmide e marca o evento final que está por vir. Tudo que aconteceu anteriormente culmina nesta única carta. Pode ser o triunfo da vontade do mal, ou do bem, mas terá apenas uma única solução no final.',
				x: 4,
				y: 1,
			},
		],
	},
	'i6-castle-ravenloft': {
		value: 'i6-castle-ravenloft',
		label: 'I6: Castelo Ravenloft',
		description: 'Leitura de cinco cartas para localizar Strahd, seus objetivos e relíquias.',
		columns: 3,
		rows: 3,
		positions: [
			{
				id: 'strahd-location',
				deck: 'both',
				name: 'Strahd',
				text: 'Carta 1: Esta carta determina onde está escondido o próprio Strahd.',
				x: 2,
				y: 2,
			},
			{
				id: 'strahd-goal',
				deck: 'both',
				name: 'Objetivo de Strahd',
				text: 'Carta 2: Esta carta determina os objetivos de Strahd.',
				x: 2,
				y: 3,
			},
			{
				id: 'strahd-tome',
				deck: 'both',
				name: 'Tomo de Strahd',
				text: 'Carta 3: Esta carta determina onde está escondido o Tomo de Strahd.',
				x: 1,
				y: 2,
			},
			{
				id: 'holy-symbol',
				deck: 'both',
				name: 'Símbolo Sagrado',
				text: 'Carta 4: Esta carta determina onde está escondido o Símbolo Sagrado.',
				x: 2,
				y: 1,
			},
			{
				id: 'sun-sword',
				deck: 'both',
				name: 'Espada do Sol',
				text: 'Carta 5: Esta carta determina onde está escondida a Espada do Sol.',
				x: 3,
				y: 2,
			},
		],
	},
};

export const READING_SPREAD_OPTIONS = Object.values(READING_SPREADS);

const GENERIC_SIMPLE_CROSS: ReadingSpreadConfig = {
	...READING_SPREADS['simple-cross'],
	positions: [
		{
			id: 'focus',
			deck: 'both',
			name: 'Foco',
			text: 'Carta 1: É a carta do foco. Ela reflete o alvo de cuja informação é buscada. Esta carta não é sorteada aleatoriamente, mas é selecionada do baralho de acordo com o alvo da busca e posicionada na posição 1. Explique aos jogadores que está carta é o nexo por onde as outras cartas irão se formar.',
			x: 2,
			y: 2,
		},
		{
			id: 'past',
			deck: 'both',
			name: 'Passado',
			text: 'Carta 2: Representa o passado. Conta um pouco da história da carta de foco. Normalmente a correlação entre o significado desta carta com a carta de foco é fácil de ser fabricada. Se nenhuma relação óbvia ocorrer, o Mestre pode dizer que há ainda um mistério que os jogadores ainda não resolveram. Mais tarde, eventos podem ser desenvolvidos para dar significado a esta carta.',
			x: 2,
			y: 3,
		},
		{
			id: 'opposition',
			deck: 'both',
			name: 'Oposição',
			text: 'Carta 3: Indica coisas que são opostas ao foco. Sua natureza reflete coisas que podem dar errado, indivíduos que possam desafiar o foco, ou a influência de qualquer tipo de resultados negativos.',
			x: 1,
			y: 2,
		},
		{
			id: 'future',
			deck: 'both',
			name: 'Futuro',
			text: 'Carta 4: Representa o futuro. Ela adverte possíveis desastres e faz promessas de triunfos futuros. Seu significado é sempre alvo de especulações, pois as ações do foco podem alterar a leitura do tarokka.',
			x: 2,
			y: 1,
		},
		{
			id: 'ally',
			deck: 'both',
			name: 'Aliado',
			text: 'Carta 5: Marca aquilo que é amigo ou aliado do foco. Indica as forças que irão beneficiar o foco na busca por seu objetivo final. Marca as forças a favor da carta do foco.',
			x: 3,
			y: 2,
		},
	],
};

const DND35_SIMPLE_CROSS: ReadingSpreadConfig = {
	...READING_SPREADS['simple-cross'],
	positions: [
		{
			id: 'focus',
			deck: 'both',
			name: 'O Foco',
			text: 'Carta 1 - O Foco: Esta carta representa a pessoa que faz as perguntas ou a pergunta que ela faz. O leitor deve escolher o cartão mais adequado e colocá-la sobre a mesa na posição central do layout.',
			x: 2,
			y: 2,
		},
		{
			id: 'past',
			deck: 'both',
			name: 'O Passado',
			text: 'Carta 2 - O Passado: Esta carta representa quaisquer influências do passado no foco da leitura.',
			x: 1,
			y: 2,
		},
		{
			id: 'present',
			deck: 'both',
			name: 'O Presente',
			text: 'Carta 3 - O Presente: Esta carta indica a situação atual ou quaisquer influências atuais.',
			x: 2,
			y: 1,
		},
		{
			id: 'future',
			deck: 'both',
			name: 'O Futuro',
			text: 'Carta 4 - O Futuro: Esta carta fornece uma indicação de eventos futuros, incluindo possíveis aliados ou inimigos.',
			x: 3,
			y: 2,
		},
		{
			id: 'outcome',
			deck: 'both',
			name: 'O Resultado',
			text: 'Carta 5 - O Resultado: Esta carta dá uma indicação geral do resultado da situação em foco.',
			x: 2,
			y: 3,
		},
	],
};

const DND35_TOWER: ReadingSpreadConfig = {
	...READING_SPREADS.tower,
	rows: 6,
	cardHeight: 'min(12vh, 116px)',
	cardWidth: 'min(8.6vh, 83px)',
	positions: [
		{
			id: 'focus',
			deck: 'both',
			name: 'O Foco',
			text: 'Carta 1 - O Foco: Esta carta representa a pessoa que faz as perguntas ou a pergunta que ela faz. O leitor deve escolher o cartão mais adequado e colocá-la sobre a mesa na posição central do layout.',
			x: 2,
			y: 3,
		},
		{
			id: 'past',
			deck: 'both',
			name: 'O Passado',
			text: 'Carta 2 - O Passado: Esta carta representa quaisquer influências do passado no foco da leitura.',
			x: 1,
			y: 4,
		},
		{
			id: 'present',
			deck: 'both',
			name: 'O Presente',
			text: 'Carta 3 - O Presente: Esta carta indica a situação atual ou quaisquer influências atuais.',
			x: 3,
			y: 4,
		},
		{
			id: 'future',
			deck: 'both',
			name: 'O Futuro',
			text: 'Carta 4 - O Futuro: Esta carta fornece uma indicação de eventos futuros, incluindo possíveis aliados ou inimigos.',
			x: 2,
			y: 2,
		},
		{
			id: 'outcome',
			deck: 'both',
			name: 'O Resultado',
			text: 'Carta 5 - O Resultado: Esta carta dá uma indicação geral do resultado da situação em foco.',
			x: 2,
			y: 5,
		},
		{
			id: 'beginnings',
			deck: 'both',
			name: 'Começos',
			text: 'Carta 6 - Começos: Este cartão indica a causa raiz da situação atual.',
			x: 1,
			y: 6,
		},
		{
			id: 'distant-past',
			deck: 'both',
			name: 'O Passado Distante',
			text: 'Carta 7 - O Passado Distante: Esta carta designa um evento ou pessoa no passado distante que tem relevância para a situação.',
			x: 2,
			y: 6,
		},
		{
			id: 'near-past',
			deck: 'both',
			name: 'O Passado Próximo',
			text: 'Carta 8 - O Passado Próximo: Esta carta ilumina eventos recentes ou pessoas pertinentes à situação.',
			x: 3,
			y: 6,
		},
		{
			id: 'future-option-left',
			deck: 'both',
			name: 'Possibilidade futura',
			text: 'Carta 9 a 11 oferecem três possibilidades futuras distintas. Futuros alternativos podem ocorrer dependendo das ações dos heróis. Esse padrão pode adicionar um senso de urgência, especialmente se você empilhar o baralho com a morte como uma das opções.',
			x: 1,
			y: 1,
		},
		{
			id: 'future-option-center',
			deck: 'both',
			name: 'Possibilidade futura',
			text: 'Carta 9 a 11 oferecem três possibilidades futuras distintas. Futuros alternativos podem ocorrer dependendo das ações dos heróis. Esse padrão pode adicionar um senso de urgência, especialmente se você empilhar o baralho com a morte como uma das opções.',
			x: 2,
			y: 1,
		},
		{
			id: 'future-option-right',
			deck: 'both',
			name: 'Possibilidade futura',
			text: 'Carta 9 a 11 oferecem três possibilidades futuras distintas. Futuros alternativos podem ocorrer dependendo das ações dos heróis. Esse padrão pode adicionar um senso de urgência, especialmente se você empilhar o baralho com a morte como uma das opções.',
			x: 3,
			y: 1,
		},
	],
};

export const getReadingSpread = (
	spread?: ReadingSpread,
	gameSystem?: GameSystem,
): ReadingSpreadConfig => {
	if ((spread ?? 'simple-cross') === 'tower' && gameSystem === 'dnd35') {
		return DND35_TOWER;
	}

	if ((spread ?? 'simple-cross') === 'simple-cross' && gameSystem === 'dnd35') {
		return DND35_SIMPLE_CROSS;
	}

	if ((spread ?? 'simple-cross') === 'simple-cross' && gameSystem && gameSystem !== 'dnd5e') {
		return GENERIC_SIMPLE_CROSS;
	}

	return READING_SPREADS[spread ?? 'simple-cross'] ?? READING_SPREADS['simple-cross'];
};

export const layout = READING_SPREADS['simple-cross'].positions;

export const cardStyles = {
	color: {
		baseURL: 'modules/leitura-de-tarokka/assets/img/color/',
		extension: '.webp',
	},
	grayscale: {
		baseURL: 'modules/leitura-de-tarokka/assets/img/grayscale/',
		extension: '.webp',
	},
	standard: {
		baseURL: 'modules/leitura-de-tarokka/assets/img/standard/',
		extension: '.svg',
	},
};

export const standardMap = {
	abjurer: '4C',
	anarchist: '6H',
	artifact: '1J',
	avenger: 'AS',
	back: '1B',
	beast: 'JD',
	beggar: '6D',
	berserker: '6S',
	bishop: '8H',
	'broken-one': 'KD',
	charlatan: '7H',
	conjurer: '9C',
	darklord: 'KS',
	dictator: '8S',
	diviner: '2C',
	donjon: 'KC',
	druid: '5H',
	elementalist: '5C',
	enchanter: '3C',
	evoker: '6C',
	executioner: 'JS',
	ghost: 'KH',
	'guild-member': '5D',
	healer: '3H',
	'hooded-one': '7S',
	horseman: '2J',
	illusionist: '7C',
	innocent: 'QH',
	marionette: 'JH',
	mercenary: '4S',
	merchant: '4D',
	miser: '9D',
	missionary: '2H',
	mists: 'QS',
	monk: 'AH',
	myrmidon: '5S',
	necromancer: '8C',
	paladin: '2S',
	philanthropist: '2D',
	priest: '10H',
	raven: 'QC',
	rogue: '10D',
	seer: 'JC',
	shepherd: '4H',
	soldier: '3S',
	swashbuckler: 'AD',
	'tax-collector': '8D',
	tempter: 'QD',
	thief: '7D',
	torturer: '9S',
	trader: '3D',
	traitor: '9H',
	transmuter: 'AC',
	warrior: '10S',
	wizard: '10C',
};
